### ISSUE TITLE
Leitor/Exibidor

### ISSUE THREAD

**Issue by Dayof** [Markuus13/jvm-sb#3]
- Patrícia 

| Tipo | Constant Pool | Attribute | Field | Method |
|-------|---------------|-----------|-------|--------|
| String | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Inteiro | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Array Unidimensional | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |

- Marcus 

| Tipo | Constant Pool | Attribute | Field | Method |
|-------|---------------|-----------|-------|--------|
| Simulação de impressão | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Arrays multidimensionais | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Float | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |

- Leonardo

| Tipo | Constant Pool | Attribute | Field | Method |
|-------|---------------|-----------|-------|--------|
| Double | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Herança | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Reescrita | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |

- Gabriel 

| Tipo | Constant Pool | Attribute | Field | Method |
|-------|---------------|-----------|-------|--------|
| Métodos estáticos | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Atributos de classe | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Polimorfismo | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |

- Dayanne

| Tipo | Constant Pool | Attribute | Field | Method |
|-------|---------------|-----------|-------|--------|
| Métodos dinâmicos | <ul><li> [ ] </li></ul>  | <ul><li> [ ] </li></ul>  | <ul><li> [ ] </li></ul> | <ul><li> [ ] </li></ul> |
| Atributos de instância | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul>  | <ul><li> [x] </li></ul> | <ul><li> [x] </li></ul> |
| Objetos | <ul><li> [ ] </li></ul>  | <ul><li> [ ] </li></ul>  | <ul><li> [ ] </li></ul> | <ul><li> [ ] </li></ul> |

Obs.: Para marcar um tipo de dado completo edite esta issue, não só marque o item com clique.

**Comment by Dayof** [comment]
Passo a passo para teste do Leitor/Exibidor:

- Gera ``.java`` do tipo de dado que está responśavel e compila para ``.class``
- Coloca a opção no menu de controle [src/ClassFilePrinter.c](src/ClassFilePrinter.c)
- Execute o ``make`` e teste para constant pool, attribute, field  e method.

**Comment by marcusborges1** [comment]
[test/FloatDemo.class](https://github.com/Markuus13/jvm-sb/blob/master/test/FloatDemo.class) e [test/java/FloatDemo.java](https://github.com/Markuus13/jvm-sb/blob/master/test/java/FloatDemo.class) adicionados. Constant Pool do FloatDemo testado e lendo de acordo. :+1:

**Comment by Dayof** [comment]
Nem tudo foi completado, mas foda-se ele vai sortear a nota mesmo...
