### ISSUE TITLE
ÚLTIMA ENTREGA

### ISSUE THREAD

**Issue by Dayof** [Markuus13/jvm-sb#6]
## Corretude do interpretador 

- [x] array simples
- [ ] arrays.length
- [ ] arrays multidimensionais
- [ ] arrays de referencia
- [x] doubles
- [x] floats (rodou apenas float_aritmetica)
- [x] longs
- [x] inteiros  
- [x] shorts
- [ ] strings
- [ ] desvios com cat 1 
- [x] operacoes logicas com cat 1  
- [ ] operacoes de deslocamento com cat 1 
- [ ] operacoes aritmeticas de cat 2 
- [ ] operacoes de deslocamento de longs
- [x] system.out.println (int, float, string e booleano)
- [x] conversao de e para cat 2
- [ ] iteracao e case
- [ ] fields
- [ ] interfaces
- [ ] recursao
- [ ] metodos estaticos  
- [ ] metodos nao estaticos
- [ ] objetos 
- [ ] operacoes de retorno
- [ ] operacoes de manipulacao de pilha
- [ ] consistencia
- [ ] exceptions

Bonus: 10% (bonus sobre a corretude do interpretador)

### Opcionais, todas as demais instruções:

- [ ] threads
- [ ] debug
- [ ] chamadas às bibliotecas do Java
- [ ] checagem dinâmica de tipos
- [ ] coletor de lixo.

- Atribuição de nota para o interpretador:
```
0,1*leitor_exibidor + 0,4*corretude + 0,4*defesa do interpretador + 0,1*site
```

## Leitura do formato .class:

- [x] Trata versões superiores? 
  - [x] teste com arquivo vetor2-java6
  - [x] java 7 versão 51 no major version
- [x] Despreza silenciosamente atributos não tratados? 
- [x] Consistência? 
  - [x] testa cafebabe
  - [x] checa classe vs arquivo
  - [x] testa case
- [ ] Corretude?
  - [ ] tratar índices de dois bytes parêmetro de instrução (exibidor)
  - [ ] trata corretamente índices de goto (exibidor)
- [ ] Exibe mnemônicos? 
  - [ ] redireciona os indices para o CP
- [x] Apresenta reindireção das entradas no Constant Pool? 
  - [x] numeração em decimal em vez de hexadecimal nos primeiros 19 slots do CP do vetor .class

- [ ] Melhorar > nota: 1,5 * 100 / 6 = 25

## Site

- [ ] Apresenta o DCM e a descrição de cada função?
- [ ] Contem a relação das estruturas de dados e os arquivos?
- [ ] Está atualizado?
- [ ] Corretude

**Comment by Dayof** [comment]
[DoubleDemo.class](test/DoubleDemo.class) com declaração, definição, operações aritméticas de soma/subtração/divisão/multiplicação/resto, cast de int, cast de long, cast de float, cast de short, método estático com retorno de double com argumento double.

**Comment by marcusborges1** [comment]
[FloatDemo.class](test/FloatDemo.class) com declaração, definição, operações aritméticas de soma/subtração/divisão/multiplicação, cast de int, cast de long, cast de float, método estático com retorno de float com argumento float.

**Comment by Dayof** [comment]
[ShortDemo.class](test/ShortDemo.class) com declaração, definição, operações aritméticas de soma/subtração/divisão/multiplicação/resto, cast de int, cast de long, cast de float, cast de double, método estático com retorno de short com argumento short.

**Comment by Dayof** [comment]
[ArrayUniDemo.class](test/ArrayUniDemo.class) Arrays de inteiro/long/short/float/double com declaração/definição por construtor, declaração/definição por alocação de memória e inicialização posterior e acesso por índice.

**Comment by Dayof** [comment]
Nem tudo foi completado, mas foda-se ele vai sortear a nota mesmo...
